{% set version = "1.0.8.dev0" %}
{% set commit = "b80bfdc34da508c247bb2124b6cc5f025c4f1b46" %}

package:
  name: basemap-data-hires
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/matplotlib/basemap/archive/{{ commit }}.tar.gz
  sha256: fe697260e981135d1fe86f3560ff581ed5239239697b9b17d14890c3b897156e

build:
  number: 2

requirements:
  build:
    - basemap >1.0.7
  run:
    - basemap >1.0.7

test:
  imports:
    - mpl_toolkits.basemap

about:
  home: http://matplotlib.org/basemap
  license: GPL-2.0
  summary: 'Plot on map projections (with coastlines and political boundaries) using matplotlib.'

extra:
  recipe-maintainers:
    - ocefpaf
