{% set version = "1.1.0" %}

package:
  name: basemap-data-hires
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}.tar.gz
  sha256: 6acdc3a08bfcebf0a1b52a05d73d51b7aa5e7240fedfa95537c92d16f2ef8778

build:
  number: 0

requirements:
  build:
    - basemap >1.0.7
  run:
    - basemap >1.0.7

test:
  imports:
    - mpl_toolkits.basemap

about:
  home: http://matplotlib.org/basemap
  license: GPL-2.0
  license_file: LICENSE_data
  summary: 'Plot on map projections (with coastlines and political boundaries) using matplotlib.'

extra:
  recipe-maintainers:
    - ocefpaf
