{% set version = "1.2.0" %}

package:
  name: basemap-data-hires
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}rel.tar.gz
  sha256: bd5bf305918a2eb675939873b735238f9e3dfe6b5c290e37c41e5b082ff3639a

build:
  number: 0

requirements:
  build:
    - basemap >1.0.7
  run:
    - basemap >1.0.7

test:
  imports:
    - mpl_toolkits.basemap

about:
  home: http://matplotlib.org/basemap
  license: GPL-2.0
  license_file: LICENSE_data
  summary: 'Plot on map projections (with coastlines and political boundaries) using matplotlib.'

extra:
  recipe-maintainers:
    - ocefpaf
