{% set version = "1.2.2" %}

package:
  name: basemap-data-hires
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}rel.tar.gz
  sha256: 7e6ee5d03b10168862cff82bfa819df8264c04f078eac4549a22dd2631696613

build:
  number: 0

requirements:
  build:
    - basemap >=1.2.1
  run:
    - basemap >=1.2.1

test:
  imports:
    - mpl_toolkits.basemap

about:
  home: http://matplotlib.org/basemap
  license: GPL-2.0
  license_file: LICENSE_data
  summary: Plot on map projections (with coastlines and political boundaries) using matplotlib.

extra:
  recipe-maintainers:
    - ocefpaf
