{% set version = "1.2.1" %}

package:
  name: basemap-data-hires
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}rel.tar.gz
  sha256: 3fb30424f18cd4ffd505e30fd9c810ae81b999bb92f950c76553e1abc081faa7

build:
  number: 0

requirements:
  build:
    - basemap >1.0.7
  run:
    - basemap >1.0.7

test:
  imports:
    - mpl_toolkits.basemap

about:
  home: http://matplotlib.org/basemap
  license: GPL-2.0
  license_file: LICENSE_data
  summary: 'Plot on map projections (with coastlines and political boundaries) using matplotlib.'

extra:
  recipe-maintainers:
    - ocefpaf
