
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ADjT9pllHlotFQgGsWTFZIS5DzY1ZblE2hfr3JFozFUgM2er7uaytyvK3PW3ft3jgBWO4ZmCDKeH/o8eZxcbRpzLP+W91fUME2bvm06/rrD0kKpA2E7OVShywbV/E83MjAEevlylxi7U4oiOSQfJGr4AR5D3RNbrlstlQ72YRYg5FHGfx87rLNKUm0q0BTUsJtBW0DI8A1uNOfNoYHk9PnxkRu34qHgONLQP/60Kb6d1Cu0Kuu8WZyztaTHPHQHUNIa1vF6vx2P3R8DaNaS91mbMzTmqEjt82h4DoR75KZIda/VsiJthE/MiOP7+ba+qy0PjfsgaGhved8xR66nkTxU644HWlG5uxoAeigGfcJOJ2xWe6kPPJVRqqio+9TF72FBtIlkUANgwHuX9R473iNgh2x5fuECZhfr32HfsagbQSpUFYrE7Jr2D71zZlkodJV0Qa4N3vYy6ItEIEZ+1IXpOcIab2f+FFVJHYDz4ObhF8bq73rTRVRTjeq0JCxv1t4LA6cu7p8RBdFhylONjDVZ2P4EwaVHAYlKzED+q9YUoAHH3vKVhDxm+JGS0V/3LUIY+eZLvosFxNWtWxQWAaurVJFYQv2V61cIf8WhFXDefSRfMOmiJJ7dAHFjX9kaxk+RrBGk1fMpxxe+l9zf0/30guB/0obwR6lrp84zJUes="


install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client

      
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
