travis:
  secure:
    BINSTAR_TOKEN: pimtqMNCxQTD/fyyMR8qtm5e4fL8UkYgnomBDD2fWFTK2tW0MPFX+mbAFGlnJQeDIFVjyPqrytH5RwjZnAPg/JOiJ6b+PxczSUKXhtqrvsd9QNcEXbjCvbz1IaOTr4T8Gw8oPzvDKaaGdMs/zaJPIcpNmv9IuFjvyLN+NpD5A6IqvOg3HSXokuFawtE3Lk+NmD7aH2AOChidXYKfww+bDGH9n8xN/YxSd904rpY7a222Kcx22zFl6C12pqAPXlFjE/cRwL0Il3CvcEKw1YmHuDESZXsezRH0DgWaj0hlF5HAzmj21BssywTjrtB9vPuaGRepIc3hnzBh1acejcA8VMB4OIEzYuo7/r0zQkgZcRKQViZ9f+2o8VC7RlWEsoCCQpVafkb8Yi1iM5c0uYt5UI6gjwVsZUiikXyUw9+LRLrBjal1Uu1XHdf/EaV4H0flqwlwYaue4AFwhJ5abYTkD5s602kRnzI/pmO1E2Y8jDT/x0n8yQqjtu8DvoqOpmIMXsgze5+RKX/NaUZicXie3ZHMbZzz7K0rAEyQT7l3ttkDtUxlP1H7N1hzIWfIOHPVAkjqNcIeAVUWbq6jKRMLx1cTH5nxduUWOoX1OHXtMd9+Mirm9dxV5Td+OpsLGVsrJ2fTmWY/GyMyiUVSaqCHlHoTHEpRoJRhQiuxOGmLuq0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
