travis:
  secure:
    BINSTAR_TOKEN: ADjT9pllHlotFQgGsWTFZIS5DzY1ZblE2hfr3JFozFUgM2er7uaytyvK3PW3ft3jgBWO4ZmCDKeH/o8eZxcbRpzLP+W91fUME2bvm06/rrD0kKpA2E7OVShywbV/E83MjAEevlylxi7U4oiOSQfJGr4AR5D3RNbrlstlQ72YRYg5FHGfx87rLNKUm0q0BTUsJtBW0DI8A1uNOfNoYHk9PnxkRu34qHgONLQP/60Kb6d1Cu0Kuu8WZyztaTHPHQHUNIa1vF6vx2P3R8DaNaS91mbMzTmqEjt82h4DoR75KZIda/VsiJthE/MiOP7+ba+qy0PjfsgaGhved8xR66nkTxU644HWlG5uxoAeigGfcJOJ2xWe6kPPJVRqqio+9TF72FBtIlkUANgwHuX9R473iNgh2x5fuECZhfr32HfsagbQSpUFYrE7Jr2D71zZlkodJV0Qa4N3vYy6ItEIEZ+1IXpOcIab2f+FFVJHYDz4ObhF8bq73rTRVRTjeq0JCxv1t4LA6cu7p8RBdFhylONjDVZ2P4EwaVHAYlKzED+q9YUoAHH3vKVhDxm+JGS0V/3LUIY+eZLvosFxNWtWxQWAaurVJFYQv2V61cIf8WhFXDefSRfMOmiJJ7dAHFjX9kaxk+RrBGk1fMpxxe+l9zf0/30guB/0obwR6lrp84zJUes=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
