travis:
  secure:
    BINSTAR_TOKEN: eCeB0MrQhMTOSccLvU+RXGlyZvIBce/K+voCpwNokw9QgTtuRRCsAsjNEnfWBniyBkKyWbXZwx79gLbd1yrJru5AL3Vrg3V876erV3hlimAM0lpmWUR1/Zwc1BUP4rK80VaFUQbAaKb2NkmnDMWZPGUlD6EEH4Bi7b8GqQyjbSbCVCy6JRBn66+44SrMA8NMko1kpDtE1mgED8sYffrRW4WU+J0iqfG9O7OLeJ04F1hLsgh6LL3kzd/QUOIjHIikqhp3//4S4E8iJyORx6boYuU+Eg3Lb9qq0LkI3PWeJHpZVl8kdd1ZxcGF9MRVIrJyNs6n386nNTLBevBQ36oRTvViHA2DHGvaypUzsvm+e5URjaZfYdaCbFDbhKrK/wKtWuBwfffTc8JXAWS7qnI5BgGNtls8c0GGGXadDS0S5D/e9lVqQve0Ug38Mmg5d0ZP/etzbIaJkMhxTwJRoTkgribccX2sxvsUFZKhZo+3RY2OPtPwnMat0REZ5fq0/S8fcR75t5wKjIv/Z8MVygxcpVe4EvtR8XX7KDwTOJbDsbyw1RD2qJjCGZaAW+9BsL9vjEBcQj7NqVLVodIYshf8mybmu4xcu6i3puAUlWKjZt3VG82FpiRUHAfzkpCjjwyLZInuDvQONLN+YD3S2ADIODoYt2wIlMmfLfBbRhXVS+E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  osx: azure
  linux: azure
  win: azure

conda_forge_output_validation: false
